/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skncoe.tnp.tpo.placed;

import com.skncoe.tnp.models.AppearingStudent;
import com.skncoe.tnp.common.MySqlConnect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

public class UpdatePlacedStudentsJframe extends javax.swing.JFrame {

    Connection conn = MySqlConnect.getConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    int tpo_id;
    int dep_id;

    /**
     * Creates new form TPO_students_schedule
     */
    public UpdatePlacedStudentsJframe(Integer tpo) {
        initComponents();
        setDefaultCloseOperation(UpdatePlacedStudentsJframe.HIDE_ON_CLOSE);
        tpo_id = tpo;
        conn = MySqlConnect.getConnection();
        String Sql = "select d_id from TPO where tpo_id='" + tpo_id + "'";
        try {
            pst = conn.prepareStatement(Sql);
            rs = pst.executeQuery();
            rs.next();
            dep_id = rs.getInt(1);

        } catch (Exception e) {
            e.printStackTrace();
        }
        Show_Student_In_JTable();
        this.labelApplicationIdError.setVisible(false);
        this.labelDesignationError.setVisible(false);
        this.labelPackageError.setVisible(false);
    }

    public ArrayList<AppearingStudent> getScheduleList() {
        ArrayList<AppearingStudent> scheduleList = new ArrayList<AppearingStudent>();

        String query = "select distinct appearing.application_id,"
                + " schedule_company_view.sch_id,"
                + " schedule_company_view.co_name,"
                + " student_person_view.full_name,"
                + " schedule_company_view.sch_date"
                + " from appearing,schedule_company_view,student_person_view"
                + " where"
                + " student_person_view.d_id='" + dep_id + "' "
                + " AND appearing.sch_id=schedule_company_view.sch_id"
                + " AND appearing.stu_id=student_person_view.stu_id";

        Statement st;
        ResultSet rs;

        try {
            st = conn.createStatement();
            rs1 = st.executeQuery(query);
            AppearingStudent user;
            while (rs1.next()) {
                user = new AppearingStudent(
                        rs1.getInt(1),
                        rs1.getInt(2),
                        rs1.getString(3),
                        rs1.getString(4),
                        rs1.getString(5)
                );

                scheduleList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return scheduleList;
    }

    public void Show_Student_In_JTable() {
        ArrayList<AppearingStudent> list1 = getScheduleList();
        DefaultTableModel model = (DefaultTableModel) jTableAppearingStudents.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list1.size(); i++) {
            row[0] = list1.get(i).getApplicationID();
            row[1] = list1.get(i).getScheduleID();
            row[2] = list1.get(i).getCompany();
            row[3] = list1.get(i).getStudentFullName();
            row[4] = list1.get(i).getDate();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPaneAppearingStudents = new javax.swing.JScrollPane();
        jTableAppearingStudents = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparatorScheduleID = new javax.swing.JSeparator();
        jLabelApplicationID = new javax.swing.JLabel();
        labelApplicationIdError = new javax.swing.JLabel();
        applicationIDTextField = new javax.swing.JTextField();
        jSeparatorScheduleID1 = new javax.swing.JSeparator();
        jLabelDesignation = new javax.swing.JLabel();
        labelDesignationError = new javax.swing.JLabel();
        designationTextField = new javax.swing.JTextField();
        jSeparatorScheduleID2 = new javax.swing.JSeparator();
        jLabelPackage = new javax.swing.JLabel();
        labelPackageError = new javax.swing.JLabel();
        packageTextField = new javax.swing.JTextField();
        placedButtonPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update placed students");

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(null);

        jTableAppearingStudents.setBackground(new java.awt.Color(36, 47, 65));
        jTableAppearingStudents.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableAppearingStudents.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTableAppearingStudents.setForeground(java.awt.Color.white);
        jTableAppearingStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Application ID", "Schedule ID", "Company", "Student", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAppearingStudents.setRowHeight(20);
        jScrollPaneAppearingStudents.setViewportView(jTableAppearingStudents);

        jPanel2.add(jScrollPaneAppearingStudents);
        jScrollPaneAppearingStudents.setBounds(40, 30, 890, 220);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mark student as placed");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(370, 270, 190, 20);

        jSeparatorScheduleID.setBackground(new java.awt.Color(36, 47, 65));
        jSeparatorScheduleID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparatorScheduleID);
        jSeparatorScheduleID.setBounds(410, 340, 210, 20);

        jLabelApplicationID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelApplicationID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApplicationID.setText("Application ID :");
        jPanel2.add(jLabelApplicationID);
        jLabelApplicationID.setBounds(247, 310, 130, 24);

        labelApplicationIdError.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelApplicationIdError.setForeground(new java.awt.Color(230, 49, 29));
        labelApplicationIdError.setText("labelIdError");
        jPanel2.add(labelApplicationIdError);
        labelApplicationIdError.setBounds(410, 350, 310, 24);

        applicationIDTextField.setBackground(new java.awt.Color(36, 47, 65));
        applicationIDTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        applicationIDTextField.setForeground(java.awt.Color.white);
        applicationIDTextField.setBorder(null);
        applicationIDTextField.setCaretColor(java.awt.Color.white);
        applicationIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationIDTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(applicationIDTextField);
        applicationIDTextField.setBounds(410, 300, 210, 30);

        jSeparatorScheduleID1.setBackground(new java.awt.Color(36, 47, 65));
        jSeparatorScheduleID1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparatorScheduleID1);
        jSeparatorScheduleID1.setBounds(410, 420, 210, 20);

        jLabelDesignation.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelDesignation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesignation.setText("Designation :");
        jPanel2.add(jLabelDesignation);
        jLabelDesignation.setBounds(250, 390, 107, 24);

        labelDesignationError.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelDesignationError.setForeground(new java.awt.Color(230, 49, 29));
        labelDesignationError.setText("labelIdError");
        jPanel2.add(labelDesignationError);
        labelDesignationError.setBounds(410, 430, 310, 24);

        designationTextField.setBackground(new java.awt.Color(36, 47, 65));
        designationTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        designationTextField.setForeground(java.awt.Color.white);
        designationTextField.setBorder(null);
        designationTextField.setCaretColor(java.awt.Color.white);
        designationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(designationTextField);
        designationTextField.setBounds(410, 380, 210, 30);

        jSeparatorScheduleID2.setBackground(new java.awt.Color(36, 47, 65));
        jSeparatorScheduleID2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparatorScheduleID2);
        jSeparatorScheduleID2.setBounds(410, 510, 210, 10);

        jLabelPackage.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelPackage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPackage.setText("Package :");
        jPanel2.add(jLabelPackage);
        jLabelPackage.setBounds(250, 480, 80, 24);

        labelPackageError.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelPackageError.setForeground(new java.awt.Color(230, 49, 29));
        labelPackageError.setText("labelIdError");
        jPanel2.add(labelPackageError);
        labelPackageError.setBounds(410, 520, 310, 24);

        packageTextField.setBackground(new java.awt.Color(36, 47, 65));
        packageTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        packageTextField.setForeground(java.awt.Color.white);
        packageTextField.setBorder(null);
        packageTextField.setCaretColor(java.awt.Color.white);
        packageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(packageTextField);
        packageTextField.setBounds(410, 470, 210, 30);

        placedButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        placedButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        placedButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placedButtonPanelMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 47, 65));
        jLabel3.setText("Mark placed");

        javax.swing.GroupLayout placedButtonPanelLayout = new javax.swing.GroupLayout(placedButtonPanel);
        placedButtonPanel.setLayout(placedButtonPanelLayout);
        placedButtonPanelLayout.setHorizontalGroup(
            placedButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placedButtonPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        placedButtonPanelLayout.setVerticalGroup(
            placedButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placedButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(placedButtonPanel);
        placedButtonPanel.setBounds(380, 580, 150, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applicationIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applicationIDTextFieldActionPerformed

    private void designationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designationTextFieldActionPerformed

    private void packageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageTextFieldActionPerformed

    private void placedButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placedButtonPanelMouseClicked
        //TODO: Add validation
        String applicationID = applicationIDTextField.getText();
        String designation = designationTextField.getText();
        String pkg = packageTextField.getText();
        // TODO: Check whether application ID correct
        String query = "select distinct sch_id, stu_id from appearing"
                + " where"
                + " application_id='" + applicationID + "' ";
        Statement st;
        ResultSet rs;
        int scheduleID = -1, studentID = -1;
        try {
            st = conn.createStatement();
            rs1 = st.executeQuery(query);
            AppearingStudent user;
            while (rs1.next()) {
                scheduleID = rs1.getInt(1);
                studentID = rs1.getInt(2);
                break;
            }
            if (scheduleID == -1) {
                JOptionPane.showMessageDialog(
                        null,
                        "No such application ID",
                        "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                query = "Insert into candidate("
                        + "designation, package, sch_id,stu_id)"
                        + " values('" + designation + "','"
                        + pkg + "','" + scheduleID + "','" + studentID + "')";

                st = null;
                try {
                    st = conn.createStatement();
                    st.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Update successful!");
                    this.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Unable to update", "Error", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_placedButtonPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePlacedStudentsJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePlacedStudentsJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePlacedStudentsJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePlacedStudentsJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //   new TPO_students_schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField applicationIDTextField;
    private javax.swing.JTextField designationTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApplicationID;
    private javax.swing.JLabel jLabelDesignation;
    private javax.swing.JLabel jLabelPackage;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneAppearingStudents;
    private javax.swing.JSeparator jSeparatorScheduleID;
    private javax.swing.JSeparator jSeparatorScheduleID1;
    private javax.swing.JSeparator jSeparatorScheduleID2;
    private javax.swing.JTable jTableAppearingStudents;
    private javax.swing.JLabel labelApplicationIdError;
    private javax.swing.JLabel labelDesignationError;
    private javax.swing.JLabel labelPackageError;
    private javax.swing.JTextField packageTextField;
    private javax.swing.JPanel placedButtonPanel;
    // End of variables declaration//GEN-END:variables
}
