/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skncoe.tnp.tpo.students;

import com.skncoe.tnp.common.MySqlConnect;
import com.skncoe.tnp.models.Student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

public class StudentsListJframe extends javax.swing.JFrame {

    Connection conn = MySqlConnect.getConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form TPO_student_details
     */
    int tpo_id;
    int dep_id;

    public StudentsListJframe(Integer tpo) {
        initComponents();
        setDefaultCloseOperation(StudentsListJframe.HIDE_ON_CLOSE);
        tpo_id = tpo;
        String Sql = "select d_id from TPO where tpo_id='" + tpo_id + "'";
        try {
            pst = conn.prepareStatement(Sql);
            rs = pst.executeQuery();
            rs.next();
            dep_id = rs.getInt(1);

        } catch (Exception e) {
            e.printStackTrace();
        }
        Show_Student_In_JTable();
    }

    public ArrayList<Student> getStudentList() {
        ArrayList<Student> studentList = new ArrayList<Student>();

        String query = "SELECT * FROM  `student_person_view` where d_id = '" + dep_id + "' and active=1";
        Statement st;
        ResultSet rs;

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);
            Student user;
            while (rs.next()) {
                user = new Student();

                user.setMarksFirstYear(rs.getInt("FE"));
                user.setMarksSecondYear(rs.getInt("SE"));
                user.setMarksThirdYear(rs.getInt("TE"));
                user.setUsername(rs.getString("username"));
                user.setDate(rs.getString("academic_year"));
                user.setFirstName(rs.getString("full_name"));
                user.setStudentId(rs.getInt("stu_id"));

                studentList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return studentList;
    }

    public void Show_Student_In_JTable() {
        ArrayList<Student> list1 = getStudentList();
        DefaultTableModel model = (DefaultTableModel) jTableStudentList.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list1.size(); i++) {

            row[0] = list1.get(i).getStudentId();
            row[1] = list1.get(i).getFirstName();
            row[2] = list1.get(i).getMarksFirstYear();
            row[3] = list1.get(i).getMarksSecondYear();
            row[4] = list1.get(i).getMarksThirdYear();
            row[5] = list1.get(i).getUsername();
            row[6] = list1.get(i).getDate();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPaneStudentList = new javax.swing.JScrollPane();
        jTableStudentList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Students");

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(null);

        jTableStudentList.setBackground(new java.awt.Color(36, 47, 65));
        jTableStudentList.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTableStudentList.setForeground(java.awt.Color.white);
        jTableStudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "FE marks", "SE marks", "TE marks", "Student Username", "Student Acad_Year"
            }
        ));
        jTableStudentList.setRowHeight(20);
        jScrollPaneStudentList.setViewportView(jTableStudentList);

        jPanel3.add(jScrollPaneStudentList);
        jScrollPaneStudentList.setBounds(40, 40, 880, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsListJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsListJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsListJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsListJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //                new TPO_student_details().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPaneStudentList;
    private javax.swing.JTable jTableStudentList;
    // End of variables declaration//GEN-END:variables
}
