DELIMITER $$

DROP TRIGGER IF EXISTS TNP.person_BEFORE_INSERT$$
USE `TNP`$$
CREATE DEFINER = CURRENT_USER TRIGGER `TNP`.`person_BEFORE_INSERT` BEFORE INSERT ON `person` FOR EACH ROW
BEGIN
	SET NEW.fname = CONCAT( UPPER(LEFT(NEW.fname, 1)), LOWER(SUBSTRING(NEW.fname FROM 2)) );
	SET NEW.lname = CONCAT( UPPER(LEFT(NEW.lname, 1)), LOWER(SUBSTRING(NEW.lname FROM 2)) );
END$$
DELIMITER ;

