/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skncoe.tnp.common.registration;

import com.skncoe.tnp.common.MySqlConnect;
import com.skncoe.tnp.models.PersonalDetails;
import com.skncoe.tnp.common.Utils;
import com.skncoe.tnp.models.TPO;
import java.sql.Connection;
import java.text.SimpleDateFormat;

public class RegistrationFormPage2TPOJframe extends javax.swing.JFrame {

    PersonalDetails person;
    Connection conn = MySqlConnect.getConnection();

    public RegistrationFormPage2TPOJframe(PersonalDetails person) {
        initComponents();
        this.person = person;
    }

    public RegistrationFormPage2TPOJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_desig = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField_salary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_dep = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        nextButtonPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Designation : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 80, 110, 24);

        jComboBox_desig.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox_desig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TPO Co-ordinator", "Assistant Co-ordinator" }));
        jComboBox_desig.setBorder(null);
        jPanel2.add(jComboBox_desig);
        jComboBox_desig.setBounds(210, 80, 210, 28);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salary : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 170, 66, 24);

        jTextField_salary.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_salary.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_salary.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_salary.setBorder(null);
        jTextField_salary.setCaretColor(java.awt.Color.white);
        jPanel2.add(jTextField_salary);
        jTextField_salary.setBounds(210, 170, 190, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Joining Date:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 250, 105, 30);

        dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(350, 280));
        jPanel2.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(210, 250, 190, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 340, 103, 24);

        jComboBox_dep.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox_dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil", "Computer", "E&TC", "IT", "Mechanical" }));
        jComboBox_dep.setBorder(null);
        jPanel2.add(jComboBox_dep);
        jComboBox_dep.setBounds(210, 340, 190, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regStepSideTPO.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(590, 70, 256, 256);

        nextButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        nextButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonPanelMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 47, 65));
        jLabel9.setText("Next");

        javax.swing.GroupLayout nextButtonPanelLayout = new javax.swing.GroupLayout(nextButtonPanel);
        nextButtonPanel.setLayout(nextButtonPanelLayout);
        nextButtonPanelLayout.setHorizontalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextButtonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        nextButtonPanelLayout.setVerticalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel2.add(nextButtonPanel);
        nextButtonPanel.setBounds(840, 430, 97, 50);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(210, 200, 190, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regStep2Top.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveAndNext() {

        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String date = formater.format(dateChooserCombo1.getSelectedDate().getTime());

        String selectedDepartment = jComboBox_dep.getSelectedItem().toString();
        int departmentId = Utils.getDeptID(selectedDepartment);

        TPO tpo = new TPO(jComboBox_desig.getSelectedItem().toString(), date, 
                departmentId, Double.parseDouble(jTextField_salary.getText()));
        this.dispose();
        new RegistrationFormPage3Jframe("TPO", person, tpo, null).setVisible(true);

    }

    private void nextButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonPanelMouseClicked
        this.saveAndNext();
    }//GEN-LAST:event_nextButtonPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormPage2TPOJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormPage2TPOJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormPage2TPOJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormPage2TPOJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFormPage2TPOJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JComboBox<String> jComboBox_dep;
    private javax.swing.JComboBox<String> jComboBox_desig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField_salary;
    private javax.swing.JPanel nextButtonPanel;
    // End of variables declaration//GEN-END:variables
}
