/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skncoe.tnp.common.registration;

import com.skncoe.tnp.common.MySqlConnect;
import com.skncoe.tnp.models.PersonalDetails;
import com.skncoe.tnp.common.Utils;
import com.skncoe.tnp.models.Student;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class RegistrationFormPage2StudentJframe extends javax.swing.JFrame {

    /**
     * Creates new form student_register
     */
    int pid;
    Connection conn = MySqlConnect.getConnection();
    String cgpa1Str, cgpa2Str, cgpa3Str;
    double cgpa1, cgpa2, cgpa3;
    PersonalDetails personalDetails;

    public RegistrationFormPage2StudentJframe(PersonalDetails personalDetails) {
        initComponents();
        this.personalDetails = personalDetails;
        this.labelCGPA1Error.setVisible(false);
        this.labelCGPA2Error.setVisible(false);
        this.labelCGPA3Error.setVisible(false);
    }

    public RegistrationFormPage2StudentJframe() {
        initComponents();
    }

    public void executeSQlQuery(String query, String message) {
        Statement st;
        try {
            st = conn.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                JOptionPane.showMessageDialog(null, "Data " + message + " Succefully");
            } else {
                JOptionPane.showMessageDialog(null, "Data Not " + message);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldFEMarks = new javax.swing.JTextField();
        fieldSEMarks = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldTEMarks = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateChooserCombo1 = new javax.swing.JComboBox<>();
        nextButtonPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fieldDepartment1 = new javax.swing.JComboBox<>();
        labelCGPA3Error = new javax.swing.JLabel();
        labelCGPA1Error = new javax.swing.JLabel();
        labelCGPA2Error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Additional details");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Graduation Year:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 40, 160, 24);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CGPA");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(130, 220, 80, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Year/Diploma : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 270, 190, 24);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Second Year :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 330, 180, 24);

        fieldFEMarks.setBackground(new java.awt.Color(36, 47, 65));
        fieldFEMarks.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        fieldFEMarks.setForeground(java.awt.Color.white);
        fieldFEMarks.setBorder(null);
        fieldFEMarks.setCaretColor(java.awt.Color.white);
        fieldFEMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFEMarksActionPerformed(evt);
            }
        });
        jPanel2.add(fieldFEMarks);
        fieldFEMarks.setBounds(240, 270, 50, 30);

        fieldSEMarks.setBackground(new java.awt.Color(36, 47, 65));
        fieldSEMarks.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        fieldSEMarks.setForeground(java.awt.Color.white);
        fieldSEMarks.setBorder(null);
        fieldSEMarks.setCaretColor(java.awt.Color.white);
        fieldSEMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSEMarksActionPerformed(evt);
            }
        });
        jPanel2.add(fieldSEMarks);
        fieldSEMarks.setBounds(240, 330, 50, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Third Year :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 400, 95, 24);

        fieldTEMarks.setBackground(new java.awt.Color(36, 47, 65));
        fieldTEMarks.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        fieldTEMarks.setForeground(java.awt.Color.white);
        fieldTEMarks.setBorder(null);
        fieldTEMarks.setCaretColor(java.awt.Color.white);
        fieldTEMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTEMarksActionPerformed(evt);
            }
        });
        jPanel2.add(fieldTEMarks);
        fieldTEMarks.setBounds(240, 400, 50, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 130, 98, 24);

        dateChooserCombo1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dateChooserCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022" }));
        dateChooserCombo1.setBorder(null);
        dateChooserCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateChooserCombo1ActionPerformed(evt);
            }
        });
        jPanel2.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(240, 40, 168, 30);

        nextButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        nextButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonPanelMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 47, 65));
        jLabel9.setText("Next");

        javax.swing.GroupLayout nextButtonPanelLayout = new javax.swing.GroupLayout(nextButtonPanel);
        nextButtonPanel.setLayout(nextButtonPanelLayout);
        nextButtonPanelLayout.setHorizontalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextButtonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        nextButtonPanelLayout.setVerticalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel2.add(nextButtonPanel);
        nextButtonPanel.setBounds(840, 440, 97, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regStepSideStudent.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(580, 60, 256, 256);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(240, 430, 50, 10);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(240, 300, 50, 10);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(240, 360, 50, 10);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("/ 10");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(300, 400, 50, 30);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("/ 10");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(300, 270, 50, 30);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("/ 10");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(300, 330, 50, 30);

        fieldDepartment1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        fieldDepartment1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil", "Computer", "E&TC", "IT", "Mechanical" }));
        fieldDepartment1.setBorder(null);
        fieldDepartment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDepartment1ActionPerformed(evt);
            }
        });
        jPanel2.add(fieldDepartment1);
        fieldDepartment1.setBounds(240, 130, 168, 30);

        labelCGPA3Error.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelCGPA3Error.setForeground(new java.awt.Color(230, 49, 29));
        labelCGPA3Error.setText("cgpa3Error");
        jPanel2.add(labelCGPA3Error);
        labelCGPA3Error.setBounds(240, 430, 310, 24);

        labelCGPA1Error.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelCGPA1Error.setForeground(new java.awt.Color(230, 49, 29));
        labelCGPA1Error.setText("cgpa1Error");
        jPanel2.add(labelCGPA1Error);
        labelCGPA1Error.setBounds(240, 300, 310, 24);

        labelCGPA2Error.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelCGPA2Error.setForeground(new java.awt.Color(230, 49, 29));
        labelCGPA2Error.setText("cgpa2Error");
        jPanel2.add(labelCGPA2Error);
        labelCGPA2Error.setBounds(240, 360, 310, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regStep2Top.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFEMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFEMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFEMarksActionPerformed

    private void fieldSEMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSEMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSEMarksActionPerformed

    private void fieldTEMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTEMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTEMarksActionPerformed

    private void dateChooserCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateChooserCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo1ActionPerformed

    private boolean validateForm() {
        boolean isValid1 = Utils.isValidCGPA(cgpa1Str, labelCGPA1Error);
        boolean isValid2 = Utils.isValidCGPA(cgpa2Str, labelCGPA2Error);
        boolean isValid3 = Utils.isValidCGPA(cgpa3Str, labelCGPA3Error);
        return isValid1 && isValid2 && isValid3;
    }

    private void saveAndNext() {

        cgpa1Str = fieldFEMarks.getText();
        cgpa2Str = fieldSEMarks.getText();
        cgpa3Str = fieldTEMarks.getText();
        if (validateForm()) {
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateChooserCombo1.getSelectedItem().toString();

            String selectedDepartment = fieldDepartment1.getSelectedItem().toString();
            int departmentId = Utils.getDeptID(selectedDepartment);
            int isActive = 1;

            Student student = new Student(Double.parseDouble(cgpa1Str), Double.parseDouble(cgpa2Str),
                    Double.parseDouble(cgpa3Str), isActive, departmentId, date);

            this.dispose();
            new RegistrationFormPage3Jframe("Student", personalDetails, null, student).setVisible(true);
        }
    }

    private void nextButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonPanelMouseClicked
        this.saveAndNext();
    }//GEN-LAST:event_nextButtonPanelMouseClicked

    private void fieldDepartment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDepartment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDepartment1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormPage2StudentJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormPage2StudentJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormPage2StudentJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormPage2StudentJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFormPage2StudentJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dateChooserCombo1;
    private javax.swing.JComboBox<String> fieldDepartment1;
    private javax.swing.JTextField fieldFEMarks;
    private javax.swing.JTextField fieldSEMarks;
    private javax.swing.JTextField fieldTEMarks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelCGPA1Error;
    private javax.swing.JLabel labelCGPA2Error;
    private javax.swing.JLabel labelCGPA3Error;
    private javax.swing.JPanel nextButtonPanel;
    // End of variables declaration//GEN-END:variables
}
