/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skncoe.tnp.tpo.report;

import com.skncoe.tnp.common.MySqlConnect;
import com.skncoe.tnp.common.Utils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class ReportCompanywiseJframe extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    String selectedYear = "";
    DefaultComboBoxModel comboModel;

    public ReportCompanywiseJframe() {
        comboModel = new DefaultComboBoxModel(Utils.getCompaniesList());
        initComponents();

        setDefaultCloseOperation(ReportCompanywiseJframe.HIDE_ON_CLOSE);
    }

    public ArrayList<ReportStudentCountYear> getStudentList(String year) {
        ArrayList<ReportStudentCountYear> studentList = new ArrayList<ReportStudentCountYear>();
        Connection connection = MySqlConnect.getConnection();

        String yearQuery = "";

        Statement st;
        ResultSet rs = null;
        ResultSet rs1;
        try {
            st = connection.createStatement();
            String abc = "All";
            String selectedYear = comboBoxYear.getSelectedItem().toString();
            if (selectedYear.equals("All")) {
                yearQuery = "";
            } else {
                yearQuery = "and student.academic_year='" + year
                        + "'";

            }
            //String query = "select count(cand_id),schedule_company_view.co_name from candidate,"
            //        + "company,schedule_company_view where candidate.sch_id=schedule_company_view.sch_id and "
            //        + "schedule_company_view.comp_id=company.comp_id " + yearQuery + " group by schedule_company_view.co_name;";
            String query = "SELECT count(cand_id), schedule_company_view.co_name from "
                    + "candidate, schedule_company_view, student WHERE "
                    + "candidate.sch_id = schedule_company_view.sch_id AND "
                    + "candidate.stu_id = student.stu_id " + yearQuery + " group by schedule_company_view.co_name";
            rs = st.executeQuery(query);

            ReportStudentCountYear user;
            while (rs.next()) {
                user = new ReportStudentCountYear(rs.getInt("count(cand_id)"), rs.getString("schedule_company_view.co_name"));//

                studentList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return studentList;
    }

    public void showStudentsInJTable(String year) {
        ArrayList<ReportStudentCountYear> list1 = getStudentList(year);
        DefaultTableModel model = (DefaultTableModel) jTableStudentCompanyNameTable.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        Object[] row = new Object[2];
        for (int i = 0; i < list1.size(); i++) {

            row[0] = list1.get(i).getStudentCount();
            row[1] = list1.get(i).getyear();

            model.addRow(row);
        }
    }

    /**
     * ***********************************************************************************
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudentCompanyNameTable = new javax.swing.JTable();
        comboBoxYear = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabelMinSalary = new javax.swing.JLabel();
        jLabelMaxSalary = new javax.swing.JLabel();
        jTextFieldMinSalary = new javax.swing.JTextField();
        jTextFieldMaxSalary = new javax.swing.JTextField();
        comboBoxCompany = new javax.swing.JComboBox<>();
        jLabelCompany = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelTotalRecruits = new javax.swing.JLabel();
        jTextFieldRecruits = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Company statistics");

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(null);

        jTableStudentCompanyNameTable.setBackground(new java.awt.Color(36, 47, 65));
        jTableStudentCompanyNameTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTableStudentCompanyNameTable.setForeground(java.awt.Color.white);
        jTableStudentCompanyNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total Students Recruited", "Company Name"
            }
        ));
        jTableStudentCompanyNameTable.setRowHeight(20);
        jScrollPane1.setViewportView(jTableStudentCompanyNameTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 90, 750, 200);

        comboBoxYear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        comboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        comboBoxYear.setBorder(null);
        comboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxYearActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxYear);
        comboBoxYear.setBounds(380, 40, 120, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Year : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 40, 90, 20);

        jLabelMinSalary.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelMinSalary.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinSalary.setText("Min salary");
        jPanel1.add(jLabelMinSalary);
        jLabelMinSalary.setBounds(100, 430, 100, 24);

        jLabelMaxSalary.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelMaxSalary.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaxSalary.setText("Max salary");
        jPanel1.add(jLabelMaxSalary);
        jLabelMaxSalary.setBounds(400, 430, 130, 24);

        jTextFieldMinSalary.setEditable(false);
        jTextFieldMinSalary.setBackground(new java.awt.Color(36, 47, 65));
        jTextFieldMinSalary.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldMinSalary.setForeground(java.awt.Color.white);
        jPanel1.add(jTextFieldMinSalary);
        jTextFieldMinSalary.setBounds(100, 480, 110, 30);

        jTextFieldMaxSalary.setEditable(false);
        jTextFieldMaxSalary.setBackground(new java.awt.Color(36, 47, 65));
        jTextFieldMaxSalary.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldMaxSalary.setForeground(java.awt.Color.white);
        jPanel1.add(jTextFieldMaxSalary);
        jTextFieldMaxSalary.setBounds(400, 480, 140, 30);

        comboBoxCompany.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        comboBoxCompany.setModel(comboModel);
        comboBoxCompany.setBorder(null);
        comboBoxCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCompanyActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxCompany);
        comboBoxCompany.setBounds(360, 360, 360, 30);

        jLabelCompany.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelCompany.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCompany.setText("Company :");
        jPanel1.add(jLabelCompany);
        jLabelCompany.setBounds(250, 360, 130, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 620, 120, 19);

        jLabelTotalRecruits.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelTotalRecruits.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalRecruits.setText("Total Recruits");
        jPanel1.add(jLabelTotalRecruits);
        jLabelTotalRecruits.setBounds(700, 430, 160, 24);

        jTextFieldRecruits.setEditable(false);
        jTextFieldRecruits.setBackground(new java.awt.Color(36, 47, 65));
        jTextFieldRecruits.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldRecruits.setForeground(java.awt.Color.white);
        jPanel1.add(jTextFieldRecruits);
        jTextFieldRecruits.setBounds(700, 480, 140, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 320, 890, 2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxYearActionPerformed
        selectedYear = (comboBoxYear.getSelectedItem().toString());
        showStudentsInJTable(selectedYear);
    }//GEN-LAST:event_comboBoxYearActionPerformed

    public void showCompanyStats() {
        String comp;
        comp = comboBoxCompany.getSelectedItem().toString();
        String query = "select min(package),max(package),count(cand_id)"
                + " from candidate,company,schedule_company_view where candidate.sch_id=schedule_company_view.sch_id "
                + "and company.comp_id=schedule_company_view.comp_id and company.co_name='" + comp
                + "'group by company.comp_id;";
        Connection conn = MySqlConnect.getConnection();
        PreparedStatement ps;
        try {
            ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jTextFieldMinSalary.setText(rs.getString("min(package)").toString());
                jTextFieldMaxSalary.setText(rs.getString("max(package)").toString());
                jTextFieldRecruits.setText(rs.getString("count(cand_id)").toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportCompanywiseJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void comboBoxCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCompanyActionPerformed
        showCompanyStats();
    }//GEN-LAST:event_comboBoxCompanyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportCompanywiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportCompanywiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportCompanywiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportCompanywiseJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportCompanywiseJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxCompany;
    private javax.swing.JComboBox<String> comboBoxYear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCompany;
    private javax.swing.JLabel jLabelMaxSalary;
    private javax.swing.JLabel jLabelMinSalary;
    private javax.swing.JLabel jLabelTotalRecruits;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableStudentCompanyNameTable;
    private javax.swing.JTextField jTextFieldMaxSalary;
    private javax.swing.JTextField jTextFieldMinSalary;
    private javax.swing.JTextField jTextFieldRecruits;
    // End of variables declaration//GEN-END:variables
}
