/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skncoe.tnp.tpo.schedule;

import com.skncoe.tnp.common.MySqlConnect;
import com.skncoe.tnp.common.Utils;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class CreateScheduleJframe extends javax.swing.JFrame {

    /**
     * Creates new form Schedule
     */
    int tpoId;
    int comp;
    String company, cgpa, minSalary;
    Connection conn = MySqlConnect.getConnection();

    public CreateScheduleJframe(int tpoId) {
        initComponents();
        setDefaultCloseOperation(CreateScheduleJframe.HIDE_ON_CLOSE);
        this.tpoId = tpoId;
        labelMinCGPAError.setVisible(false);
        labelMinSalaryError.setVisible(false);
        jLabelTpoIdValue.setText(this.tpoId + "");
    }

    public boolean validateSalary() {
        boolean isValid = true;
        if (minSalary.length() == 0) {
            labelMinSalaryError.setText("Minimum salary is required");
            isValid = false;
        } else {
            try {
                double cgpaDouble = Double.parseDouble(cgpa);
            } catch (Exception e) {
                labelMinSalaryError.setText("Invalid minimum salary");
                isValid = false;
            }

        }
        if (!isValid) {
            labelMinSalaryError.setVisible(true);
        } else {
            labelMinSalaryError.setVisible(false);
        }

        return isValid;
    }

    private boolean validateForm() {
        boolean isValid = false;

        boolean isValidCGPA = Utils.isValidCGPA(cgpa, labelMinCGPAError);
        boolean isValidSalary = validateSalary();
        return isValidCGPA && isValidSalary;
    }

    public void executeSQlQuery(String query, String message) {
        Statement st;
        try {
            st = conn.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                JOptionPane.showMessageDialog(null, "Data " + message + " Succefully");
            } else {
                JOptionPane.showMessageDialog(null, "Data Not " + message);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelDate = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        outOf10 = new javax.swing.JLabel();
        textFieldMinCGPA = new javax.swing.JTextField();
        jLabelYear = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelMinSalary = new javax.swing.JLabel();
        jTextFieldMinSalary = new javax.swing.JTextField();
        jLabelCompanyID = new javax.swing.JLabel();
        jTextFieldCompanyID = new javax.swing.JTextField();
        jLabelTPOID = new javax.swing.JLabel();
        createButtonPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabelTpoIdValue = new javax.swing.JLabel();
        jSeparatorCompanyID = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparatorMinSalary = new javax.swing.JSeparator();
        labelMinSalaryError = new javax.swing.JLabel();
        labelMinCGPAError = new javax.swing.JLabel();
        jLabelMinCGPA = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create schedule");
        setLocation(new java.awt.Point(0, 0));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(null);

        jLabelDate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate.setText("Schedule Date : ");
        jPanel3.add(jLabelDate);
        jLabelDate.setBounds(240, 70, 150, 24);
        jPanel3.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(480, 70, 120, 30);

        outOf10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        outOf10.setForeground(new java.awt.Color(255, 255, 255));
        outOf10.setText("/ 10");
        jPanel3.add(outOf10);
        outOf10.setBounds(590, 130, 160, 24);

        textFieldMinCGPA.setBackground(new java.awt.Color(36, 47, 65));
        textFieldMinCGPA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textFieldMinCGPA.setForeground(java.awt.Color.white);
        textFieldMinCGPA.setBorder(null);
        textFieldMinCGPA.setCaretColor(java.awt.Color.white);
        textFieldMinCGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMinCGPAActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldMinCGPA);
        textFieldMinCGPA.setBounds(480, 130, 90, 30);

        jLabelYear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYear.setText("Academic Year : ");
        jPanel3.add(jLabelYear);
        jLabelYear.setBounds(240, 200, 135, 24);

        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jComboBox1.setBorder(null);
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(480, 200, 210, 30);

        jLabelMinSalary.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelMinSalary.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinSalary.setText("Minimum Salary : ");
        jPanel3.add(jLabelMinSalary);
        jLabelMinSalary.setBounds(240, 260, 142, 24);

        jTextFieldMinSalary.setBackground(new java.awt.Color(36, 47, 65));
        jTextFieldMinSalary.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldMinSalary.setForeground(java.awt.Color.white);
        jTextFieldMinSalary.setBorder(null);
        jTextFieldMinSalary.setCaretColor(java.awt.Color.white);
        jTextFieldMinSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinSalaryActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldMinSalary);
        jTextFieldMinSalary.setBounds(480, 260, 210, 30);

        jLabelCompanyID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelCompanyID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCompanyID.setText("Company ID :");
        jPanel3.add(jLabelCompanyID);
        jLabelCompanyID.setBounds(240, 360, 108, 24);

        jTextFieldCompanyID.setBackground(new java.awt.Color(36, 47, 65));
        jTextFieldCompanyID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldCompanyID.setForeground(java.awt.Color.white);
        jTextFieldCompanyID.setBorder(null);
        jTextFieldCompanyID.setCaretColor(java.awt.Color.white);
        jPanel3.add(jTextFieldCompanyID);
        jTextFieldCompanyID.setBounds(480, 360, 210, 30);

        jLabelTPOID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelTPOID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTPOID.setText("TPO ID :");
        jPanel3.add(jLabelTPOID);
        jLabelTPOID.setBounds(240, 30, 70, 24);

        createButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        createButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonPanelMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 47, 65));
        jLabel11.setText("Create");

        javax.swing.GroupLayout createButtonPanelLayout = new javax.swing.GroupLayout(createButtonPanel);
        createButtonPanel.setLayout(createButtonPanelLayout);
        createButtonPanelLayout.setHorizontalGroup(
            createButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createButtonPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        createButtonPanelLayout.setVerticalGroup(
            createButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(createButtonPanel);
        createButtonPanel.setBounds(410, 470, 110, 50);

        jLabelTpoIdValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelTpoIdValue.setForeground(java.awt.Color.white);
        jLabelTpoIdValue.setText("jLabel1");
        jPanel3.add(jLabelTpoIdValue);
        jLabelTpoIdValue.setBounds(480, 20, 90, 40);

        jSeparatorCompanyID.setBackground(new java.awt.Color(36, 47, 65));
        jSeparatorCompanyID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparatorCompanyID);
        jSeparatorCompanyID.setBounds(480, 390, 210, 10);

        jSeparator3.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(480, 160, 100, 10);

        jSeparatorMinSalary.setBackground(new java.awt.Color(36, 47, 65));
        jSeparatorMinSalary.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparatorMinSalary);
        jSeparatorMinSalary.setBounds(480, 290, 210, 10);

        labelMinSalaryError.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelMinSalaryError.setForeground(new java.awt.Color(230, 49, 29));
        labelMinSalaryError.setText("minimumSalaryError");
        jPanel3.add(labelMinSalaryError);
        labelMinSalaryError.setBounds(480, 300, 310, 24);

        labelMinCGPAError.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelMinCGPAError.setForeground(new java.awt.Color(230, 49, 29));
        labelMinCGPAError.setText("minimumCGPAError");
        jPanel3.add(labelMinCGPAError);
        labelMinCGPAError.setBounds(480, 160, 310, 24);

        jLabelMinCGPA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelMinCGPA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinCGPA.setText("Minimum CGPA : ");
        jPanel3.add(jLabelMinCGPA);
        jLabelMinCGPA.setBounds(240, 130, 160, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldMinCGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMinCGPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMinCGPAActionPerformed

    private void jTextFieldMinSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinSalaryActionPerformed

    private void createButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonPanelMouseClicked
        cgpa = textFieldMinCGPA.getText();
        minSalary = jTextFieldMinSalary.getText();
        boolean isValid = validateForm();
        if (isValid) {
            SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");

            String date = formater.format(dateChooserCombo1.getSelectedDate().getTime());
            String query1 = "INSERT INTO `schedule`(`criteria`,`min_salary`,"
                    + "`sch_date`,`comp_id`,`tpo_id`,`acad_year`) VALUES ('"
                    + textFieldMinCGPA.getText() + "','" + jTextFieldMinSalary.getText() + "','"
                    + date + "','" + jTextFieldCompanyID.getText() + "','"
                    + tpoId + "','" + jComboBox1.getSelectedItem() + "')";

            boolean scheduleCreated = MySqlConnect.executeUpdateSQlQuery(query1);
            if (scheduleCreated) {
                JOptionPane.showMessageDialog(null, "Schedule created");

            } else {
                JOptionPane.showMessageDialog(null, "Schedule creation failed", "Error", JOptionPane.ERROR_MESSAGE);

            }
            this.dispose();
        }
    }//GEN-LAST:event_createButtonPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel createButtonPanel;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabelCompanyID;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelMinCGPA;
    private javax.swing.JLabel jLabelMinSalary;
    private javax.swing.JLabel jLabelTPOID;
    private javax.swing.JLabel jLabelTpoIdValue;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparatorCompanyID;
    private javax.swing.JSeparator jSeparatorMinSalary;
    private javax.swing.JTextField jTextFieldCompanyID;
    private javax.swing.JTextField jTextFieldMinSalary;
    private javax.swing.JLabel labelMinCGPAError;
    private javax.swing.JLabel labelMinSalaryError;
    private javax.swing.JLabel outOf10;
    private javax.swing.JTextField textFieldMinCGPA;
    // End of variables declaration//GEN-END:variables
}
