/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skncoe.tnp.tpo.schedule;

import com.skncoe.tnp.common.MySqlConnect;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class DeleteScheduleJframe extends javax.swing.JFrame {

    /**
     * Deletes schedule
     */
    int tpoId;
    int comp;
    String company, idInputStr;
    Connection conn = MySqlConnect.getConnection();

    public DeleteScheduleJframe(int tpoId) {
        initComponents();
        setDefaultCloseOperation(DeleteScheduleJframe.HIDE_ON_CLOSE);
        this.tpoId = tpoId;
        this.labelIdError.setVisible(false);
    }

    public void executeSQlQuery(String query, String message) {
        Statement st;
        try {
            st = conn.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                JOptionPane.showMessageDialog(null, "Data " + message + " Succefully");
            } else {
                JOptionPane.showMessageDialog(null, "Data Not " + message);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelScheduleID = new javax.swing.JLabel();
        scheduleIDTextField = new javax.swing.JTextField();
        deleteButtonPanel = new javax.swing.JPanel();
        jLabelDelete = new javax.swing.JLabel();
        jSeparatorScheduleID = new javax.swing.JSeparator();
        labelIdError = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete schedule");

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(null);

        jLabelScheduleID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelScheduleID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelScheduleID.setText("Schedule ID :");
        jPanel3.add(jLabelScheduleID);
        jLabelScheduleID.setBounds(310, 260, 107, 24);

        scheduleIDTextField.setBackground(new java.awt.Color(36, 47, 65));
        scheduleIDTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        scheduleIDTextField.setForeground(java.awt.Color.white);
        scheduleIDTextField.setBorder(null);
        scheduleIDTextField.setCaretColor(java.awt.Color.white);
        scheduleIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleIDTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(scheduleIDTextField);
        scheduleIDTextField.setBounds(450, 250, 210, 30);

        deleteButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        deleteButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonPanelMouseClicked(evt);
            }
        });

        jLabelDelete.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelDelete.setForeground(new java.awt.Color(36, 47, 65));
        jLabelDelete.setText("Delete");

        javax.swing.GroupLayout deleteButtonPanelLayout = new javax.swing.GroupLayout(deleteButtonPanel);
        deleteButtonPanel.setLayout(deleteButtonPanelLayout);
        deleteButtonPanelLayout.setHorizontalGroup(
            deleteButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteButtonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelDelete)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        deleteButtonPanelLayout.setVerticalGroup(
            deleteButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(deleteButtonPanel);
        deleteButtonPanel.setBounds(420, 370, 110, 50);

        jSeparatorScheduleID.setBackground(new java.awt.Color(36, 47, 65));
        jSeparatorScheduleID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparatorScheduleID);
        jSeparatorScheduleID.setBounds(450, 290, 210, 20);

        labelIdError.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelIdError.setForeground(new java.awt.Color(230, 49, 29));
        labelIdError.setText("labelIdError");
        jPanel3.add(labelIdError);
        labelIdError.setBounds(450, 300, 310, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private boolean validateId() {
        boolean isValid = true;
        labelIdError.setVisible(false);
        if (idInputStr.length() == 0) {
            labelIdError.setText("ID is required");
            labelIdError.setVisible(true);
            isValid = false;
        } else {
            try {
                int idInt = Integer.parseInt(idInputStr);
            } catch (Exception e) {
                labelIdError.setText("ID should be integer");
                labelIdError.setVisible(true);
                isValid = false;
            }
        }
        return isValid;
    }


    private void deleteButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonPanelMouseClicked
        idInputStr = scheduleIDTextField.getText();

        if (validateId()) {

            String query1 = "DELETE FROM `schedule` WHERE sch_id = " + scheduleIDTextField.getText();

            boolean scheduleCreated = MySqlConnect.executeUpdateSQlQuery(query1);
            if (scheduleCreated) {
                JOptionPane.showMessageDialog(null, "Schedule deleted");
            } else {
                JOptionPane.showMessageDialog(null, "Schedule deletion failed", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_deleteButtonPanelMouseClicked

    private void scheduleIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleIDTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteScheduleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel deleteButtonPanel;
    private javax.swing.JLabel jLabelDelete;
    private javax.swing.JLabel jLabelScheduleID;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparatorScheduleID;
    private javax.swing.JLabel labelIdError;
    private javax.swing.JTextField scheduleIDTextField;
    // End of variables declaration//GEN-END:variables
}
