/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skncoe.tnp.student;

import com.skncoe.tnp.common.MySqlConnect;
import com.skncoe.tnp.models.Schedule;
import com.skncoe.tnp.common.EditProfileJframe;
import com.skncoe.tnp.common.LoginJframe;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class StudentHomePageJframe extends javax.swing.JFrame {

    /**
     * Creates new form student_file
     */
    String username;
    int studentId;
    int departmentId;
    int personId;

    public StudentHomePageJframe(String username) throws SQLException {
        initComponents();
        this.username = username;

        String getStudentDetailsQuery = "select * from student_login_view where"
                + " username='" + username + "'";
        ResultSet rs = null;
        try {
            rs = MySqlConnect.executeSelectSQlQuery(getStudentDetailsQuery);
            rs.next();
            studentId = rs.getInt(1);
            departmentId = rs.getInt(6);
            personId = rs.getInt(7);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        setDefaultCloseOperation(ScheduleRegistrationJFrame.HIDE_ON_CLOSE);

        scrollPaneScheduleTable.setVisible(false);
        panelWelcome.setVisible(true);
        labelTitle.setText("Welcome " + username + "!");

    }

    public ArrayList<Schedule> getScheduleList() {
        ArrayList<Schedule> scheduleList = new ArrayList<Schedule>();

        String getStudentRegisteredSchedules = "select * from "
                + "schedule_company_view,TPO,appearing where TPO.d_id= '"
                + departmentId + "' and active=1 "
                + " and TPO.tpo_id = schedule_company_view.tpo_id"
                + " and appearing.stu_id=" + studentId
                + " and appearing.sch_id=schedule_company_view.sch_id";

        ResultSet rs;

        try {
            rs = MySqlConnect.executeSelectSQlQuery(getStudentRegisteredSchedules);
            Schedule user;
            while (rs.next()) {
                user = new Schedule(rs.getInt("sch_id"),
                        rs.getDate("sch_date").toString(),
                        rs.getInt("comp_id"), rs.getString("co_name"),
                        rs.getInt("criteria"), rs.getDouble("min_salary"));

                scheduleList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return scheduleList;
    }

    public void hideScheduleTable() {
        scrollPaneScheduleTable.setVisible(false);
        panelWelcome.setVisible(true);
        labelTitle.setText("Welcome " + username + "!");
    }

    public void showScheduleTable() {
        scrollPaneScheduleTable.setVisible(true);
        panelWelcome.setVisible(false);
        labelTitle.setText("My schedules");

        ArrayList<Schedule> list1 = getScheduleList();
        DefaultTableModel model = (DefaultTableModel) jTable_schedule.getModel();

        for (int index = 0; index < model.getRowCount();) {
            model.removeRow(index);
        }

        Object[] row = new Object[6];
        for (int i = 0; i < list1.size(); i++) {
            row[0] = list1.get(i).getschid();
            row[1] = list1.get(i).getschdate();
            row[2] = list1.get(i).getcompid();
            row[3] = list1.get(i).getconame();
            row[4] = list1.get(i).getcriteria();
            row[5] = list1.get(i).getminsalary();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelWelcome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollPaneScheduleTable = new javax.swing.JScrollPane();
        jTable_schedule = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemRegisteredSchedule = new javax.swing.JMenuItem();
        menuItemRegister = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemEditProfile = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(36, 47, 65));
        setForeground(new java.awt.Color(36, 47, 65));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        labelTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("My schedules");

        jLayeredPane1.setBackground(new java.awt.Color(36, 47, 65));

        panelWelcome.setBackground(new java.awt.Color(36, 47, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regStepSideStudent.png"))); // NOI18N

        javax.swing.GroupLayout panelWelcomeLayout = new javax.swing.GroupLayout(panelWelcome);
        panelWelcome.setLayout(panelWelcomeLayout);
        panelWelcomeLayout.setHorizontalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelWelcomeLayout.setVerticalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTable_schedule.setBackground(new java.awt.Color(36, 47, 65));
        jTable_schedule.setForeground(new java.awt.Color(255, 255, 255));
        jTable_schedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule ID", "Schedule Date", "Company ID", "Company Name", "Criteria", "Minimum Salary"
            }
        ));
        scrollPaneScheduleTable.setViewportView(jTable_schedule);

        jLayeredPane1.setLayer(panelWelcome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(scrollPaneScheduleTable, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(scrollPaneScheduleTable, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(312, 312, 312)
                    .addComponent(panelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(316, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(scrollPaneScheduleTable, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(panelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBar.setBackground(new java.awt.Color(97, 212, 195));
        menuBar.setForeground(new java.awt.Color(36, 47, 65));
        menuBar.setPreferredSize(new java.awt.Dimension(205, 50));

        jMenu1.setForeground(new java.awt.Color(36, 47, 65));
        jMenu1.setText("Schedule");

        menuItemRegisteredSchedule.setText("My schedules");
        menuItemRegisteredSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisteredScheduleActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRegisteredSchedule);

        menuItemRegister.setText("Register");
        menuItemRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisterActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRegister);

        menuBar.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(36, 47, 65));
        jMenu2.setText("Profile");

        menuItemEditProfile.setText("Edit");
        menuItemEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditProfileActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemEditProfile);

        menuBar.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(36, 47, 65));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/180477.gif"))); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRegisteredScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisteredScheduleActionPerformed
        showScheduleTable();
    }//GEN-LAST:event_menuItemRegisteredScheduleActionPerformed

    private void menuItemEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditProfileActionPerformed
        hideScheduleTable();
        try {
            new EditProfileJframe(personId, departmentId).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(StudentHomePageJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemEditProfileActionPerformed

    private void menuItemRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisterActionPerformed
        hideScheduleTable();

        new ScheduleRegistrationJFrame(studentId, departmentId).setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_menuItemRegisterActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_jMenu3MouseClicked

    public void logout() {
        this.dispose();
        try {
            new LoginJframe().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(StudentHomePageJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHomePageJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHomePageJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHomePageJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHomePageJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable_schedule;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemEditProfile;
    private javax.swing.JMenuItem menuItemRegister;
    private javax.swing.JMenuItem menuItemRegisteredSchedule;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JScrollPane scrollPaneScheduleTable;
    // End of variables declaration//GEN-END:variables
}
